# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5074a2fccebe4fcdfa625aa668e6e172"
name = "phone-case-customizer"
application_url = "https://phone-case-customizer-sp.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://phone-case-customizer-sp.onrender.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://phone-case-customizer-sp.onrender.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,read_orders,write_orders,write_products,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://phone-case-customizer-sp.onrender.com/auth",
  "https://phone-case-customizer-sp.onrender.com/auth/callback",
  "https://phone-case-customizer-sp.onrender.com/api/auth"
]

[app_proxy]
url = "https://phone-case-customizer-sp.onrender.com/apps/customizer"
subpath = "customizer"
prefix = "apps"
